server:
  display-name: demo
  port: 8888

application:
  name: demo

spring:
  datasource:
    url: jdbc:postgresql://10.192.30.200:5432/bpmndemo
    username: pgsql
    password: Dpp-pgsql123##
    driver-class-name: org.postgresql.Driver
  activiti:
    database-schema-update: true
    check-process-definitions: false